# Generated by Django 3.1.7 on 2021-03-27 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20210327_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finances.bank'),
        ),
    ]
